# RubyGems
plugins: [jekyll-paginate, jekyll-gist]

markdown:         kramdown
permalink:        pretty


# Setup
title:            Denise Case
tagline:          ''
description:      ''
url:              
baseurl:          'http://denisecase.github.io'
port:             4000




# About/contact
author:
  name:           'Denise Case'
  url:            https://www.denisecase.com

# Custom variables
version:          0.0.2


# This website's repo
github:
  repo:           http://github.com/denisecase/denisecase.github.io
 
# exclude from the build process
exclude: 
  - README.md
  - .ruby-version
  - Gemfile
  - Gemfile.lock